### ISSUE TITLE
Potion blocking does not seem to work

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/WorldGuard#1266]
WORLDGUARD-3578 - Reported by TGS

This is my global config:

```yaml

gameplay:
    block-potions: [BLINDNESS, ABSORPTION, CONFUSION, DAMAGE_RESISTANCE, FAST_DIGGING, FIRE_RESISTANCE, HARM, HEAL, HEALTH_BOOST, HUNGER, INCREASE_DAMAGE, INVISIBILITY, POISON, REGENERATION, SATURATION, SLOW, SLOW_DIGGING, WATER_BREATHING, WEAKNESS, WITHER]
    block-potions-overly-reliably: true
```

I tried both with block-potions-overly-reliably: true and false.
Running 6.1.1- SNAPSHOT.1623-96e0ffd

People can still throw potions and the effects apply. Maybe it's because the potions have multiple effects instead of one?
