### ISSUE TITLE
spigot 1.9 Potion

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/WorldGuard#1304]
WORLDGUARD-3652 - Reported by sat

on 1.9 deny use of potion is non working.

on 1.8 i set in config.yml :
```

gameplay:
    block-potions:
    - INVISIBILITY
    block-potions-overly-reliably: true
```

All method for use invisibility potion are inefficient. (that good)
But on 1.9 potion, splash, zone, on hand or in dispenser all work again :(
