### ISSUE TITLE
Time-lock flag does not set when logging into the region.

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/WorldGuard#1417]
WORLDGUARD-3893 - Reported by mibby

WorldGuard 6.2.2 dev 1709
Paper dev 1238 (Spigot 1.12.2)

If you log into the server inside a region that has a time-lock flag set, the time does not get sent to your client. Instead you get the time of the current world. Leaving and re-entering the region, the correct time-lock time applies to the client.

```

use-player-move-event: true
use-player-teleports: true
```

```

    spawn:
        min: {x: -216.0, y: 0.0, z: -166.0}
        max: {x: 252.0, y: 255.0, z: 179.0}
        members: {}
        flags:
            time-lock: '62500'
        owners: {}
        type: cuboid
        priority: 1
```

I did set the gamerule doDaylightCycle false in the world because seeing the sky constantly move and flicker back a few ticks was obnoxious. The region has the time set to night while the rest of the world has a time frozen at day. 

Is the player login not providing worldguard a teleport event when logging into the region perhaps?
