### ISSUE TITLE
You get teleported in the air when entering a region with a horse

### ISSUE THREAD

**Issue by Leguan16** [EngineHub/WorldGuard#2003]
### WorldEdit Version

7.2.14

### WorldGuard Version

7.0.7

### Platform Version

Paper-521

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When I set up a region with the flag `entry: deny` and try to enter the region with a player - that is not allowed to enter that region-  sitting on a horse I get teleported in the air 

https://user-images.githubusercontent.com/59799222/235199086-da73cad4-baa8-4d63-91ec-b3d0531f4be0.mp4

### Expected Behavior

I expect to not be teleported in the air.

### Reproduction Steps

1. set up a region 
2. add flag `entry: deny`
3. mount a hourse 
4. try enter the region

### Optional WorldGuard-Report

https://paste.enginehub.org/R3KV-TKM1.report

### Anything Else?

Here is the region config:
```yml
regions:
    test:
        min: {x: -50, y: 63, z: -180}
        max: {x: -47, y: 67, z: -176}
        members: {}
        flags: {entry: deny}
        owners: {}
        type: cuboid
        priority: 0
```
