### ISSUE TITLE
Extend Falling Block Physics Settings to Include All Blocks

### ISSUE THREAD

**Issue by Timtendo12** [EngineHub/WorldGuard#2066]
### The Problem

Currently, we're limited to disabling the falling physics solely for Sand and Gravel. This limitation excludes other blocks such as Concrete Powder.

### A Solution

Expand the block physics setting to encompass all falling blocks, ensuring consistency.

Currently, it looks like this:
```yml
physics:
    no-physics-gravel: true
    no-physics-sand: true
```

### Alternatives

Introducing options for additional falling blocks to provide control over their physics.

### Anything Else?

No further adjustments needed.
