### ISSUE TITLE
WorldGuard 6.0 - PVP flag is ignored.

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/WorldGuard#976]
WORLDGUARD-3150 - Reported by rtcabooservb

Using WorldGuard 6.0 dev 1435.

I have PVP flagged as deny in my __global__ region to block pvp fighting by default. This way I can control where players can actually fight. However, it seems anyone can pvp anywhere, regardless of the PVP flag set. The global pvp: deny flag is not blocking pvp combat.

```

    __global__:
        members: {}
        flags:
            use: allow
            blocked-cmds: [/op, /version, /reload, //sel, //;, /pl, /sel, /;, /plugins,
                /stop]
            pvp: deny
        owners: {}
        type: global
        priority: 0
```
